spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dine_ease?rewriteBatchedStatements=true
    username: root
    password: Evie998659!
  mvc:
    path match:
      matching-strategy: ant_path_matcher
